version: "3"

services:
  db:
    image: mysql:5.6
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    network_mode: host
    volumes:
      - ./data/mysql/:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=restroomrate
      - MYSQL_ROOT_PASSWORD=root

  web:
    image: node
    restart: always
    command: npm run prod
    network_mode: host
    depends_on:
      - db
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
